In [0]:
from google.colab import drive 
drive.mount('/content/gdrive/')

In [0]:
import random

In [0]:
#트레인 데이터와 밸리드 데이터를 불러옴

import os
import numpy as np
import random

from torch.utils.data import Dataset
from torch.utils.data import DataLoader
data_review = os.path.join("./gdrive",'My Drive','dataset','train_data')
data_label = os.path.join("./gdrive",'My Drive','dataset','train_label')
fr=open(data_review, 'rt', encoding='utf-8')
fl=open(data_label,'rt',encoding = 'utf-8')
dr=fr.readlines()
dl=fl.readlines()

pdata=[]
s_u_m=0
for i in range(len(dr)):
  pdata.append((dr[i].split('\n')[0],dl[i].split('\n')[0]))
  s_u_m+=len(dr[i].split('\n')[0])
print(s_u_m//len(dr))
pdata

data_review = os.path.join("./gdrive",'My Drive','dataset','valid_data')
data_label = os.path.join("./gdrive",'My Drive','dataset','valid_label')
fr=open(data_review, 'rt', encoding='utf-8')
fl=open(data_label,'rt',encoding = 'utf-8')
dr=fr.readlines()
dl=fl.readlines()

vdata=[]
s_u_m=0
for i in range(len(dr)):
  vdata.append((dr[i].split('\n')[0],dl[i].split('\n')[0]))
  s_u_m+=len(dr[i].split('\n')[0])
vdata

33


[('억지설정에눈물짜깁기한게 아니던데요. 정말 잘봤어요. 배우들 연기 최고!', '9'),
 ('보면서 전혀 억지라는 생각이 들지 않았던 영화에요. 평소에 영화보다가 현실적이지 않은 장면이 나오면 흥미가 확 떨어졌었는데, 억지스러울 수 있는 내용을 전혀 억지스럽지않게 잘 풀어낸 영화 같아요. 배우들의 연기도 한 몫 한 것 같습니다. 잘봤습니다.',
  '10'),
 ('영화를 보고 평점 등록하긴하나? 감성팔이니 유치하니 감수성이 말라있나 ㅡ,.ㅡ 교도소 감옥 바탕으로 이런 소재로 영화화 해서 웃음과 감동을 주는 영화 실로 처음이다 몇년만인지 눈물이 상영 내내 흐르더라 본인외에 영화보는 사람 모두 다..',
  '10'),
 ('많은내용을담은영화.. 배우들의연기와 내용이 잘 전달된것같아서 좋앗어여', '10'),
 ('경찰청장[배역] 씹어먹을인간. 폭행 및 공갈협박죄, 공무집행방해로 징역 10년을 처하라.', '8'),
 ('웃기고 슬프고 화나고', '10'),
 ('원래 슬픈영화잘안보는데... 류승룡나온다고해서 보러갔다가 울뻔했다;;', '10'),
 ('ㅜㅜ', '10'),
 ('유치하던데', '6'),
 ('돈주고안아까운영화진심..눈물참느라죽는줄', '10'),
 ('음 뭔가 딱히. .. 다운받아서 볼만한 영화라는 생각이 마니들었음.. 슬프긴 한대... 뭔가 무리한 설정?', '7'),
 ('전문가들은뭘기준으로평점을먹이는지는모르지만이영화는9점이상짜리가확실하다류승용과아역연기만봐도10점은줘야된다', '10'),
 ('정의에 이름으로.. 오글거려 죽는줄 알았네요.', '6'),
 ('아 눈물도 안나오고...솔직히 가족이랑 편하게 보긴 좋았지만....류승룡의 역할에 대한 연기는 매우 실망이었다.', '3'),
 ('웃음,  감동 .., 그러나 역시나 끝에는 전형적인 한국영화의 유치한 감성팔이', '8'),
 ('진짜재밋어요ㅠㅠ', '10'),
 ('굿', '10'),
 ('울었뜸', '10'),
 ('다시또보고싶은영화', '10'),
 ('와... 울뻔했어요 흑흑

In [0]:
num1=[]
num2=[]
num3=[]
num4=[]
num5=[]
num6=[]
num7=[]
num8=[]
num9=[]
num0=[]
for i in range(len(pdata)):
  if int(pdata[i][1])==1:
    num1.append(i)
  elif int(pdata[i][1])==2:
    num2.append(i)
  elif int(pdata[i][1])==3:
    num3.append(i)
  elif int(pdata[i][1])==4:
    num4.append(i)
  elif int(pdata[i][1])==5:
    num5.append(i)
  elif int(pdata[i][1])==6:
    num6.append(i)
  elif int(pdata[i][1])==7:
    num7.append(i)
  elif int(pdata[i][1])==8:
    num8.append(i)
  elif int(pdata[i][1])==9:
    num9.append(i)
  elif int(pdata[i][1])==10:
    num0.append(i)
print(num1[0],num2[0],num3[0],num4[0],num5[0],num6[0],num7[0],num8[0],num9[0],num0[0])

7 3221 3244 895 284 10 277 23 1 0


In [0]:
data_review = os.path.join("./gdrive",'My Drive','dataset','test_data')
data_label = os.path.join("./gdrive",'My Drive','dataset','valid_label')
fr=open(data_review, 'rt', encoding='utf-8')
fl=open(data_label,'rt',encoding = 'utf-8')
dr=fr.readlines()
dl=fl.readlines()
print(len(dr))
tdata=[]
s_u_m=0
for i in range(len(dr)):
  tdata.append((dr[i].split('\n')[0]))
  s_u_m+=len(dr[i].split('\n')[0])
tdata

400000


['진짜 가만히 있어도 눈물이 나옵니다...ㅠㅠㅠㅠㅠㅠ',
 '영화를 분석하며 보는 불쌍한 사람이 되지 마세요. 아이 키우는 아빠로서 많은 눈물을 흘렸습니다.',
 '정말 다시보고싶은영화   적극추천합니다배우들연기 짱  기대이상입니다',
 '대박 ㅠㅠ웃음에서감동까지 최고의영화입니다',
 '감동있지만 개인적으로 지적장애로 유발된 웃음은 싫어하는터라..',
 '그냥대박 미침',
 '말이 필요 없습니다. 평점 믿고라도  일단 보세요. 이런 영화 없습니다.',
 '너무  감동적이랍니다류승룡씨 등등   연기력이 한몫한듯해여   울고  웃고  스트레스한방에  날리고왔답니다',
 '그냥 대박',
 '완전너무감동적이고재미잇어요',
 '너무끝내주는영화였어욬ㅋㅋ10점만점에10점인가슴찡한영화였습니다',
 '최고임 진짜ㅠㅡㅠ 정신놓고 울고옴ㅋㅋ',
 '영화 하모니랑 스토리가 비슷한것같아요ㅋㅋ 그래도 진짜눈물을 멈출수가없었네요ㅋㅋ',
 '경찰청장 개OO끼',
 '7년만에 눈물 흘리게 만든 영화',
 '최고근래들어 박수건달 베를린 보다재밌고슬프다몇년만에영화보고펑펑울다왔쯤',
 '최고',
 '정말 가슴이 먹먹해지는.. 보고나서도 행복해지는 영화',
 '진짜진짜 최고의 영화',
 '오늘보고왔는데..저는 슬픈영화봐도 눈물안흘리는 사람인데..마지막엔 참을수가없더라구요ㅋㅋ간만에 잼있는영화봤네요^^',
 '진짜슬프고재밋게밧어요ㅠㅠ본영화중에제일슬픈듯ㅠㅠ흑흑거리면서울엇는데..한번더보러가고싶네요ㅠㅠ',
 'ㅜㅜ',
 '너무너무너무재밌어요',
 '그냥 말이 필요없습니다영화보고 통곡한건 어렷을때 그린마일 이란영화말곤 첨이네요아빠에대한 따듯함 사랑 애절함 아낌...영화끝나고 나와서도 10분은 울엇던영화내일또보러갑니당~~~~',
 '웃음 감동 모두 있는 작품, 여러 배우들의 연기력이 특히 눈에 띄는 작품이네요. 좋은 작품 감사합니다.',
 '남자로써 눈물나는 영화보긴 오랜만이네',
 '영화 상영후 일주일이 지나고 평점을 남깁니다. 한마디로 표현 하자면 심장의 온도가 2도씨는 올라가는 영화 입니다.아직도 눈물

In [0]:
#시험적인 CNN을 만들어 테스트를 진행함

import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        print(x)
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        print(x)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))

        x = F.relu(self.fc2(x))
        x = self.fc3(x)

        return x
    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features

In [0]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(device)

cuda:0


In [0]:
#글자를 벡터화 시키는 char2vec함수, 그리고 그것을 기반으로 문장 전체를 벡터화시키는 함수

def char2vec(char):
  v=[]
  idx=ord(char)
  if ord('가')<= idx<=ord('힣'):
    f=idx - ord('가')
    s=f//28
    t=f%28
    f=s//21
    s=s%21
    t=t-1
    v.append(f)
    v.append(s)
    v.append(t)
  elif idx < 128:
    v.append(67+idx)
    v.append(-1)
    v.append(-1)
  elif ord('ㄱ')<idx<ord('ㅣ'):
    v.append(67+128+idx-12593)
    v.append(-1)
    v.append(-1)
  elif idx == ord('♡'):
    v.append(67 + 128 + 51)
    v.append(-1)
    v.append(-1)
  elif idx == ord('♥'):
    v.append(67 + 128 + 51)
    v.append(-1)
    v.append(-1)
  elif idx == ord('★'):
    v.append(67 + 128 + 51)
    v.append(-1)
    v.append(-1)
  elif idx == ord('☆'):
    v.append(67 + 128 + 51)
    v.append(-1)
    v.append(-1)
  else:
    v.append(-1)
    v.append(-1)
    v.append(-1)
  return v

print(char2vec("恨"))
print('a')


def str2vec(str,maxlen):
  v=[]
  if len(str)>=maxlen:
    l=maxlen
    
    for i in range(l):
      v.append(char2vec(str[i]))
  elif len(str)<maxlen:
    l=len(str)
    
    for i in range(l):
      v.append(char2vec(str[i]))
    for j in range(maxlen-l):
      v.append([-1,-1,-1])
  return torch.from_numpy(np.array(v)).float()

a=np.array(str2vec("가나다라",4),dtype=np.double)
print(a)
a=torch.from_numpy(a)
print(len(a.numpy()[0]))

#문장의 글자를 n글자씩 묶어서 문장벡터를 변형해주는 함수, 논문에 있는 내용을 참고함
def transformWithNgram(t,n):
  h,w=t.size()
  #a=t.numpy()
  res=[]
  
  for i in range(h+1-n):
    tmp=[]
    for j in range(n):
      for k in range(len(a[0])):
        tmp.append(int(t[i+j,k]))
    res.append(tmp)
  res=[[res]]
  return torch.from_numpy(np.array(res,dtype=np.double)).float()

test=transformWithNgram(a,3)
print(test.size())

[-1, -1, -1]
a
[[ 0.  0. -1.]
 [ 2.  0. -1.]
 [ 3.  0. -1.]
 [ 5.  0. -1.]]
3
torch.Size([1, 1, 2, 9])


In [0]:
#문장분류를 위한 CNN

class CFSC(nn.Module):
    def __init__(self):
        super(CFSC, self).__init__()
        self.conv3 = nn.Conv2d(1,10,(1,9))
        self.conv4 = nn.Conv2d(1,10,(1,12))
        self.conv5 = nn.Conv2d(1,10,(1,15))
        self.fc1=nn.Linear(30,64)
        
        self.Dropout=nn.Dropout(p=0.5)
        self.fc2=nn.Linear(64,32)
        self.fc3=nn.Linear(32,10)
    def forward(self,x):
        #x=x.cpu()
        a1,a2,a3,a4=x.size()
        x=x.view(a3,a4)
        
        input3=transformWithNgram(x,3)
        input4=transformWithNgram(x,4)
        input5=transformWithNgram(x,5)
        '''input3=input3.cuda()
        input4=input4.cuda()
        input5=input5.cuda()'''
        
        x=F.relu(self.conv3(input3))
        x1,x2,x3,x4=x.size()
        x=x.view(x1,x2,x4,x3)
        x=F.max_pool2d(x,(1,x3))
        x=x.view(-1,x2)

        y=F.relu(self.conv4(input4))
        y1,y2,y3,y4=y.size()
        y=y.view(y1,y2,y4,y3)
        y=F.max_pool2d(y,(1,y3))
        y=y.view(-1,y2)

        z=F.relu(self.conv5(input5))
        z1,z2,z3,z4=z.size()
        z=z.view(z1,z2,z4,z3)
        z=F.max_pool2d(z,(1,z3))
        z=z.view(-1,z2)

        out=torch.cat((x,y),0)
        out=torch.cat((out,z),0)
        out=out.view(-1,x2+y2+z2)
        out=self.Dropout(F.relu(self.fc1(out)))
        out=self.Dropout(F.relu(self.fc2(out)))
        out=self.fc3(out)
        
        return out
    




In [0]:
!nvidia-smi
!ls ./gdrive/'My Drive'

In [0]:
model=CFSC()
model.to(device)

CFSC(
  (conv3): Conv2d(1, 10, kernel_size=(1, 9), stride=(1, 1))
  (conv4): Conv2d(1, 10, kernel_size=(1, 12), stride=(1, 1))
  (conv5): Conv2d(1, 10, kernel_size=(1, 15), stride=(1, 1))
  (fc1): Linear(in_features=30, out_features=64, bias=True)
  (Dropout): Dropout(p=0.5, inplace=False)
  (fc2): Linear(in_features=64, out_features=32, bias=True)
  (fc3): Linear(in_features=32, out_features=10, bias=True)
)

In [0]:
path=os.path.join('./gdrive','My Drive','dataset','normal.pt')
model.load_state_dict(torch.load(path))

<All keys matched successfully>

In [0]:
path=os.path.join('./gdrive','My Drive','dataset','Revise.pt')

torch.save(model.state_dict(),path)

In [0]:
path=os.path.join('./gdrive','My Drive','dataset','challenge.pt')

#model.load_state_dict(a)
for i in range(100):
  print('------------------------------------------------')
  print(i)
  print()
  criterion = nn.CrossEntropyLoss()
  optimizer = torch.optim.SGD(model.parameters(), lr=0.001)
  scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 10, gamma=0.5)
  model = train_model(model,criterion,optimizer,scheduler,25)
  
  '''s_u_m=0
  model.eval()
  for i in range(10000):
    #print(i)
    with torch.no_grad():
      review,label=vdata[i]
      review=str2vec(review,33)
      h,w=review.size()
      review=review.view(1,1,h,w)
      review=review.cuda()
      #review.to(device)
      label_pred=model(review)
      #print(int(label))
      #print(int(label_pred.argmax(1))+1)
      if int(label_pred.argmax(1)+1)==int(label):
        #print(int(label))
        s_u_m+=1
    if i%10000==9999:
      print(i+1)
      #print(criterion(label_pred,torch.empty(1, dtype=torch.long).random_(5)))
  print(s_u_m/10000)
  print(s_u_m)'''
  

  torch.save(model.state_dict(),path)


------------------------------------------------
0

Epoch 1/25
trainning
1000
evaluating
10000
0.007
70
Epoch 2/25
trainning
1000
evaluating
10000
0.0065
65
Epoch 3/25
trainning
1000
evaluating
10000
0.0065
65
Epoch 4/25
trainning
1000
evaluating
10000
0.0066
66
Epoch 5/25
trainning
1000
evaluating
10000
0.0065
65
Epoch 6/25
trainning


In [0]:
def train_model(model,criterion,optimizer,scheduler,num_epochs):
  #since=time.time()

  for epoch in range(num_epochs):
    print('Epoch {}/{}'.format(epoch+1,num_epochs))
    
    model.train()
    print("trainning")
    for i in range(1000):
      if i%10==0:
        tmp=random.randrange(0,len(num1))
        idx=num1[tmp]
      elif i%10==1:
        tmp=random.randrange(0,len(num2))
        idx=num2[tmp]
      elif i%10==2:
        tmp=random.randrange(0,len(num3))
        idx=num3[tmp]
      elif i%10==3:
        tmp=random.randrange(0,len(num4))
        idx=num4[tmp]
      elif i%10==4:
        tmp=random.randrange(0,len(num5))
        idx=num5[tmp]
      elif i%10==5:
        tmp=random.randrange(0,len(num6))
        idx=num6[tmp]
      elif i%10==6:
        tmp=random.randrange(0,len(num7))
        idx=num7[tmp]
      elif i%10==7:
        tmp=random.randrange(0,len(num8))
        idx=num8[tmp]
      elif i%10==8:
        tmp=random.randrange(0,len(num9))
        idx=num9[tmp]
      elif i%10==9:
        tmp=random.randrange(0,len(num0))
        idx=num0[tmp]
      #idx=random.randrange(0,9000000)
      if i%1000==999:
        print(i+1)
      review = pdata[idx][0]
      review=str2vec(review,33)
      h,w=review.size()
      review=review.view(1,1,h,w)
      #review=review.cuda()
      #labels = torch.empty(1, dtype=torch.long).random_(5)
      labels=int(pdata[idx][1])-1
      tmp=torch.empty(1,dtype=torch.long)
      tmp[0]=labels
      labels=tmp
      #labels=labels.cuda()
      #print(type(labels))
      optimizer.zero_grad()
      with torch.set_grad_enabled(True):
        outputs=model(review)
      #print(outputs)
      
        loss=criterion(outputs,labels)
        loss.backward()
        optimizer.step()
    s_u_m=0
    model.eval()
    print("evaluating")
    for i in range(10000):
      #print(i)
      with torch.no_grad():
        review,label=vdata[i]
        review=str2vec(review,33)
        h,w=review.size()
        review=review.view(1,1,h,w)
        #review=review.cuda()
        #review.to(device)
        with torch.no_grad():
          label_pred=model(review)
        #print(int(label))
        #print(int(label_pred.argmax(1))+1)
        if int(label_pred.argmax(1)+1)==int(label):
          #print(int(label))
          s_u_m+=1
      if i%10000==9999:
        print(i+1)
        #print(criterion(label_pred,torch.empty(1, dtype=torch.long).random_(5)))
    print(s_u_m/10000)
    print(s_u_m)
    scheduler.step()
  return model



In [0]:
model = train_model(model,criterion,optimizer,scheduler,25)

Epoch 1/25
1000
Epoch 2/25
1000
Epoch 3/25
1000
Epoch 4/25
1000
Epoch 5/25
1000
Epoch 6/25
1000
Epoch 7/25
1000
Epoch 8/25
1000
Epoch 9/25
1000
Epoch 10/25
1000
Epoch 11/25
1000
Epoch 12/25
1000
Epoch 13/25
1000
Epoch 14/25
1000
Epoch 15/25
1000
Epoch 16/25
1000
Epoch 17/25
1000
Epoch 18/25
1000
Epoch 19/25
1000
Epoch 20/25
1000
Epoch 21/25
1000
Epoch 22/25
1000
Epoch 23/25
1000
Epoch 24/25
1000
Epoch 25/25
1000


In [0]:
import csv
a=os.path.join("./gdrive",'My Drive','dataset','outputFinal.csv')
f = open(a, 'w', encoding='utf-8')
wr = csv.writer(f)
#wr.writerow([1, "Alice", True])
#wr.writerow([2, "Bob", False])
#f.close()
s_u_m=0
#model.load_state_dict(torch.load(os.path.join("./gdrive",'My Drive','dataset','finalModel.pt')))
model.eval()
for i in range(400000):
  #print(i)
  with torch.set_grad_enabled(False):
    review=tdata[i]
    z=tdata[i]
    review=str2vec(review,33)
    h,w=review.size()
    review=review.view(1,1,h,w)
    label_pred=model(review)
    #print(type(int(label_pred.argmax(1)+1)))
    #break
    wr.writerow([int(label_pred.argmax(1)+1)])
    if int(label_pred.argmax(1)+1)==int(label):
      s_u_m+=1
  if i%1000==999:
    print(i+1)
    #print(criterion(label_pred,torch.empty(1, dtype=torch.long).random_(5)))
print(s_u_m/10000)
print(s_u_m)
f.close()

1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
70000
71000
72000
73000
74000
75000
76000
77000
78000
79000
80000
81000
82000
83000
84000
85000
86000
87000
88000
89000
90000
91000
92000
93000
94000
95000
96000
97000
98000
99000
100000
101000
102000
103000
104000
105000
106000
107000
108000
109000
110000
111000
112000
113000
114000
115000
116000
117000
118000
119000
120000
121000
122000
123000
124000
125000
126000
127000
128000
129000
130000
131000
132000
133000
134000
135000
136000
137000
138000
139000
140000
141000
142000
143000
144000
145000
146000
147000
148000
149000
150000
151000
152000
153000
154000
155000
156000
157000
158000
15

In [0]:
a=torch.load(os.path.join("./gdrive",'My Drive','dataset','normal.pt'))

In [0]:
s="가나다라"
type(list(s)[0])
ord(s[0])
cfsc=CFSC()
#print(cfsc(test.float()))

m=str2vec(pdata[0][0],33)
print(m)
q,w=m.size()
m=m.view(1,1,q,w)
m=cfsc(m)
print(m)

print(m.argmax(1))
#print(m.size())

#m=m.view(1,6,1,6)
#print(F.max_pool2d(m,(1,6)))

tensor([[  7.,   1.,  -1.],
        [  0.,   6.,  20.],
        [ 11.,  18.,  15.],
        [ 99.,  -1.,  -1.],
        [175.,  -1.,  -1.],
        [178.,  -1.,  -1.],
        [185.,  -1.,  -1.],
        [168.,  -1.,  -1.],
        [ 99.,  -1.,  -1.],
        [183.,  -1.,  -1.],
        [171.,  -1.,  -1.],
        [168.,  -1.,  -1.],
        [176.,  -1.,  -1.],
        [168.,  -1.,  -1.],
        [ 11.,  19.,  -1.],
        [ 99.,  -1.,  -1.],
        [  0.,   0.,  15.],
        [  3.,   8.,  20.],
        [ 12.,   4.,   0.],
        [ 11.,  20.,   3.],
        [ 99.,  -1.,  -1.],
        [  9.,   4.,   3.],
        [ 11.,  17.,   7.],
        [  0.,   9.,  -1.],
        [ 99.,  -1.,  -1.],
        [ 11.,   6.,  20.],
        [  9.,   0.,  -1.],
        [  0.,  20.,  -1.],
        [ 11.,   5.,  -1.],
        [  9.,   4.,  -1.],
        [ 99.,  -1.,  -1.],
        [  2.,   0.,  -1.],
        [ 11.,   8.,  -1.]])
tensor([[ 41.3627, -16.3248,  15.8757, -30.9192,   8.4434,  -7.8370,  22.16

In [0]:
import csv
a=os.path.join("./gdrive",'My Drive','dataset','ot.csv')
f = open(a, 'w', encoding='utf-8')
wr = csv.writer(f)
wr.writerow([1, "Alice", True])
wr.writerow([2, "Bob", False])
f.close()